/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\newDesktop\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7a4dab30",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a4dab30").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-44748af3",
    path: "/%E6%B5%8B%E8%AF%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44748af3").then(next)
    },
  },
  {
    path: "/测试.html",
    redirect: "/%E6%B5%8B%E8%AF%95.html"
  },
  {
    path: "/测试.html",
    redirect: "/%E6%B5%8B%E8%AF%95.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]